# Generated by Django 3.2.7 on 2021-11-18 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dresses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='handbag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pic')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('price', models.FloatField()),
                ('color', models.CharField(max_length=100)),
                ('material', models.CharField(max_length=100)),
                ('height', models.FloatField()),
                ('width', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='jewellery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pic')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='pic'),
        ),
        migrations.CreateModel(
            name='top',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pic')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('price', models.FloatField()),
                ('color', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('neck', models.CharField(max_length=100)),
                ('sleeve', models.CharField(max_length=100)),
                ('material', models.CharField(max_length=100)),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dresses.size')),
            ],
        ),
        migrations.CreateModel(
            name='saree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pic')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=3000)),
                ('price', models.FloatField()),
                ('color', models.CharField(max_length=500)),
                ('material', models.CharField(max_length=500)),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dresses.size')),
            ],
        ),
        migrations.CreateModel(
            name='kurtaset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pic')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=2000)),
                ('price', models.FloatField()),
                ('color', models.CharField(max_length=500)),
                ('type', models.CharField(max_length=500)),
                ('neck', models.CharField(max_length=100)),
                ('sleeve', models.CharField(max_length=100)),
                ('material', models.CharField(max_length=500)),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dresses.size')),
            ],
        ),
        migrations.CreateModel(
            name='kurta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pic')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('price', models.FloatField()),
                ('color', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('neck', models.CharField(max_length=100)),
                ('sleeve', models.CharField(max_length=100)),
                ('material', models.CharField(max_length=100)),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dresses.size')),
            ],
        ),
    ]
