# Generated by Django 3.2.7 on 2021-12-04 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dresses', '0003_handbag_length'),
    ]

    operations = [
        migrations.DeleteModel(
            name='product',
        ),
        migrations.RemoveField(
            model_name='handbag',
            name='length',
        ),
        migrations.RemoveField(
            model_name='kurta',
            name='size',
        ),
        migrations.RemoveField(
            model_name='kurtaset',
            name='size',
        ),
        migrations.RemoveField(
            model_name='saree',
            name='size',
        ),
        migrations.RemoveField(
            model_name='top',
            name='size',
        ),
        migrations.DeleteModel(
            name='Size',
        ),
    ]
